spring:
  profiles:
    active:
    - test 
---
spring:
  profi1es: dev
  application:
    name: microervicecloud-config-tb120-dev
---
spring:
  profi1es: test 
  application:
    name: microervicecloud-config-tb120-test
#注：必须是UTF-8格式：编码→使用UTF-8编码
