#必须是UTF-8格式：编码→使用UTF-8编码
spring:
  profiles:
    active:
    - dev
---
#开发环境
server:
  port: 8201
spring:
  profi1es: dev 
  application:
    name: microervicecloud-config-client
eureka:
  client:
    server-url:
      defaultZone: http://eureka-dev.com:7001/eureka/
---
#测试环境
server:
  port: 8202
spring:
  profi1es: test 
  application:
    name: microervicecloud-config-client
eureka:
  client:
    server-url:
      defaultZone: http://eureka-test.com:7001/eureka/
      
      
