spring:
  profiles:
    active:
    - test
---
server:
  port: 7001
  
spring:
  profiles: dev
  application:
    name: microservice-config-eureka
    
eureka:
  instance:
    hostname: eureka7001.com
    client: 
    register-with-eureka: false  #不要将应用注册到服务注册中心eureka：因为该应用就是服务注册中心，所以不需要把自己注册上
    fetch-registry: false        #不从服务注册中心erueka拉取注册信息
    service-url: 
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka  #设置服务注册中心eureka的注册定地址
      defaultZone: http://eureka7001.com:7001/eureka/
---
server:
  port: 7002
  
spring:
  profiles: test
  application:
    name: microservice-config-eureka
    
eureka:
  instance:
    hostname: eureka7002.com
    client: 
    register-with-eureka: false  #不要将应用注册到服务注册中心eureka：因为该应用就是服务注册中心，所以不需要把自己注册上
    fetch-registry: false        #不从服务注册中心erueka拉取注册信息
    service-url: 
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka  #设置服务注册中心eureka的注册定地址
      defaultZone: http://eureka7002.com:7002/eureka/   
      